### ISSUE TITLE
Help implementing neo-scraper

### ISSUE THREAD

**Issue by YureiDragon** [neobooru/neo-scraper#14]
I am trying to use your neo-scraper in a personal project and am having issues implementing it, do you have any documentation that could assist me?

**Comment by neobooru** [comment]
I made a [small Node.js example here](https://github.com/neobooru/neo-scraper-example). Because of some ES module fuckery the package wasn't working, so I pushed an update which _should_ fix that.

I just went ahead and assumed that you want to make a Node.js app. If you want to make an app which runs in the browser (e.g. on a website or as a browser extension) then you can remove the JSDOM package. You however still need to use `"type": "module",` in your package.json

**Comment by YureiDragon** [comment]
I am indeed making a website, I am inviting you to the repo so you can take a look at my implementation, thanks.
